=== simplr-sh/sw-api/public/api/films/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"title": {
			"type": "string"
		},
		"episode_id": {
			"type": "integer"
		},
		"opening_crawl": {
			"type": "string"
		},
		"director": {
			"type": "string"
		},
		"producer": {
			"type": "string"
		},
		"release_date": {
			"type": "string"
		},
		"characters": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"planets": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"starships": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"vehicles": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"species": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"title",
		"episode_id",
		"opening_crawl",
		"director",
		"producer",
		"release_date",
		"characters",
		"planets",
		"starships",
		"vehicles",
		"species",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/films/6.json
{
  "title": "Revenge of the Sith",
  "episode_id": 3,
  "opening_crawl": "War! The Republic is crumbling\r\nunder attacks by the ruthless\r\nSith Lord, Count Dooku.\r\nThere are heroes on both sides.\r\nEvil is everywhere.\r\n\r\nIn a stunning move, the\r\nfiendish droid leader, General\r\nGrievous, has swept into the\r\nRepublic capital and kidnapped\r\nChancellor Palpatine, leader of\r\nthe Galactic Senate.\r\n\r\nAs the Separatist Droid Army\r\nattempts to flee the besieged\r\ncapital with their valuable\r\nhostage, two Jedi Knights lead a\r\ndesperate mission to rescue the\r\ncaptive Chancellor....",
  "director": "George Lucas",
  "producer": "Rick McCallum",
  "release_date": "2005-05-19",
  "characters": [
    "https://sw.simplr.sh/api/people/1.json",
    "https://sw.simplr.sh/api/people/2.json",
    "https://sw.simplr.sh/api/people/3.json",
    "https://sw.simplr.sh/api/people/4.json",
    "https://sw.simplr.sh/api/people/5.json",
    "https://sw.simplr.sh/api/people/6.json",
    "https://sw.simplr.sh/api/people/7.json",
    "https://sw.simplr.sh/api/people/10.json",
    "https://sw.simplr.sh/api/people/11.json",
    "https://sw.simplr.sh/api/people/12.json",
    "https://sw.simplr.sh/api/people/13.json",
    "https://sw.simplr.sh/api/people/20.json",
    "https://sw.simplr.sh/api/people/21.json",
    "https://sw.simplr.sh/api/people/33.json",
    "https://sw.simplr.sh/api/people/35.json",
    "https://sw.simplr.sh/api/people/46.json",
    "https://sw.simplr.sh/api/people/51.json",
    "https://sw.simplr.sh/api/people/52.json",
    "https://sw.simplr.sh/api/people/53.json",
    "https://sw.simplr.sh/api/people/54.json",
    "https://sw.simplr.sh/api/people/55.json",
    "https://sw.simplr.sh/api/people/56.json",
    "https://sw.simplr.sh/api/people/58.json",
    "https://sw.simplr.sh/api/people/63.json",
    "https://sw.simplr.sh/api/people/64.json",
    "https://sw.simplr.sh/api/people/67.json",
    "https://sw.simplr.sh/api/people/68.json",
    "https://sw.simplr.sh/api/people/75.json",
    "https://sw.simplr.sh/api/people/78.json",
    "https://sw.simplr.sh/api/people/79.json",
    "https://sw.simplr.sh/api/people/80.json",
    "https://sw.simplr.sh/api/people/81.json",
    "https://sw.simplr.sh/api/people/82.json",
    "https://sw.simplr.sh/api/people/83.json"
  ],
  "planets": [
    "https://sw.simplr.sh/api/planets/1.json",
    "https://sw.simplr.sh/api/planets/2.json",
    "https://sw.simplr.sh/api/planets/5.json",
    "https://sw.simplr.sh/api/planets/8.json",
    "https://sw.simplr.sh/api/planets/9.json",
    "https://sw.simplr.sh/api/planets/12.json",
    "https://sw.simplr.sh/api/planets/13.json",
    "https://sw.simplr.sh/api/planets/14.json",
    "https://sw.simplr.sh/api/planets/15.json",
    "https://sw.simplr.sh/api/planets/16.json",
    "https://sw.simplr.sh/api/planets/17.json",
    "https://sw.simplr.sh/api/planets/18.json",
    "https://sw.simplr.sh/api/planets/19.json"
  ],
  "starships": [
    "https://sw.simplr.sh/api/starships/2.json",
    "https://sw.simplr.sh/api/starships/32.json",
    "https://sw.simplr.sh/api/starships/48.json",
    "https://sw.simplr.sh/api/starships/59.json",
    "https://sw.simplr.sh/api/starships/61.json",
    "https://sw.simplr.sh/api/starships/63.json",
    "https://sw.simplr.sh/api/starships/64.json",
    "https://sw.simplr.sh/api/starships/65.json",
    "https://sw.simplr.sh/api/starships/66.json",
    "https://sw.simplr.sh/api/starships/68.json",
    "https://sw.simplr.sh/api/starships/74.json",
    "https://sw.simplr.sh/api/starships/75.json"
  ],
  "vehicles": [
    "https://sw.simplr.sh/api/vehicles/33.json",
    "https://sw.simplr.sh/api/vehicles/50.json",
    "https://sw.simplr.sh/api/vehicles/53.json",
    "https://sw.simplr.sh/api/vehicles/56.json",
    "https://sw.simplr.sh/api/vehicles/60.json",
    "https://sw.simplr.sh/api/vehicles/62.json",
    "https://sw.simplr.sh/api/vehicles/67.json",
    "https://sw.simplr.sh/api/vehicles/69.json",
    "https://sw.simplr.sh/api/vehicles/70.json",
    "https://sw.simplr.sh/api/vehicles/71.json",
    "https://sw.simplr.sh/api/vehicles/72.json",
    "https://sw.simplr.sh/api/vehicles/73.json",
    "https://sw.simplr.sh/api/vehicles/76.json"
  ],
  "species": [
    "https://sw.simplr.sh/api/species/1.json",
    "https://sw.simplr.sh/api/species/2.json",
    "https://sw.simplr.sh/api/species/3.json",
    "https://sw.simplr.sh/api/species/6.json",
    "https://sw.simplr.sh/api/species/15.json",
    "https://sw.simplr.sh/api/species/19.json",
    "https://sw.simplr.sh/api/species/20.json",
    "https://sw.simplr.sh/api/species/23.json",
    "https://sw.simplr.sh/api/species/24.json",
    "https://sw.simplr.sh/api/species/25.json",
    "https://sw.simplr.sh/api/species/26.json",
    "https://sw.simplr.sh/api/species/27.json",
    "https://sw.simplr.sh/api/species/28.json",
    "https://sw.simplr.sh/api/species/29.json",
    "https://sw.simplr.sh/api/species/30.json",
    "https://sw.simplr.sh/api/species/33.json",
    "https://sw.simplr.sh/api/species/34.json",
    "https://sw.simplr.sh/api/species/35.json",
    "https://sw.simplr.sh/api/species/36.json",
    "https://sw.simplr.sh/api/species/37.json"
  ],
  "created": "2014-12-20T18:49:38.403000Z",
  "edited": "2014-12-20T20:47:52.073000Z",
  "url": "https://sw.simplr.sh/api/films/6.json"
}

=== simplr-sh/sw-api/public/api/films/5.json
{
  "title": "Attack of the Clones",
  "episode_id": 2,
  "opening_crawl": "There is unrest in the Galactic\r\nSenate. Several thousand solar\r\nsystems have declared their\r\nintentions to leave the Republic.\r\n\r\nThis separatist movement,\r\nunder the leadership of the\r\nmysterious Count Dooku, has\r\nmade it difficult for the limited\r\nnumber of Jedi Knights to maintain \r\npeace and order in the galaxy.\r\n\r\nSenator Amidala, the former\r\nQueen of Naboo, is returning\r\nto the Galactic Senate to vote\r\non the critical issue of creating\r\nan ARMY OF THE REPUBLIC\r\nto assist the overwhelmed\r\nJedi....",
  "director": "George Lucas",
  "producer": "Rick McCallum",
  "release_date": "2002-05-16",
  "characters": [
    "https://sw.simplr.sh/api/people/2.json",
    "https://sw.simplr.sh/api/people/3.json",
    "https://sw.simplr.sh/api/people/6.json",
    "https://sw.simplr.sh/api/people/7.json",
    "https://sw.simplr.sh/api/people/10.json",
    "https://sw.simplr.sh/api/people/11.json",
    "https://sw.simplr.sh/api/people/20.json",
    "https://sw.simplr.sh/api/people/21.json",
    "https://sw.simplr.sh/api/people/22.json",
    "https://sw.simplr.sh/api/people/33.json",
    "https://sw.simplr.sh/api/people/35.json",
    "https://sw.simplr.sh/api/people/36.json",
    "https://sw.simplr.sh/api/people/40.json",
    "https://sw.simplr.sh/api/people/43.json",
    "https://sw.simplr.sh/api/people/46.json",
    "https://sw.simplr.sh/api/people/51.json",
    "https://sw.simplr.sh/api/people/52.json",
    "https://sw.simplr.sh/api/people/53.json",
    "https://sw.simplr.sh/api/people/58.json",
    "https://sw.simplr.sh/api/people/59.json",
    "https://sw.simplr.sh/api/people/60.json",
    "https://sw.simplr.sh/api/people/61.json",
    "https://sw.simplr.sh/api/people/62.json",
    "https://sw.simplr.sh/api/people/63.json",
    "https://sw.simplr.sh/api/people/64.json",
    "https://sw.simplr.sh/api/people/65.json",
    "https://sw.simplr.sh/api/people/66.json",
    "https://sw.simplr.sh/api/people/67.json",
    "https://sw.simplr.sh/api/people/68.json",
    "https://sw.simplr.sh/api/people/69.json",
    "https://sw.simplr.sh/api/people/70.json",
    "https://sw.simplr.sh/api/people/71.json",
    "https://sw.simplr.sh/api/people/72.json",
    "https://sw.simplr.sh/api/people/73.json",
    "https://sw.simplr.sh/api/people/74.json",
    "https://sw.simplr.sh/api/people/75.json",
    "https://sw.simplr.sh/api/people/76.json",
    "https://sw.simplr.sh/api/people/77.json",
    "https://sw.simplr.sh/api/people/78.json",
    "https://sw.simplr.sh/api/people/82.json"
  ],
  "planets": [
    "https://sw.simplr.sh/api/planets/1.json",
    "https://sw.simplr.sh/api/planets/8.json",
    "https://sw.simplr.sh/api/planets/9.json",
    "https://sw.simplr.sh/api/planets/10.json",
    "https://sw.simplr.sh/api/planets/11.json"
  ],
  "starships": [
    "https://sw.simplr.sh/api/starships/21.json",
    "https://sw.simplr.sh/api/starships/32.json",
    "https://sw.simplr.sh/api/starships/39.json",
    "https://sw.simplr.sh/api/starships/43.json",
    "https://sw.simplr.sh/api/starships/47.json",
    "https://sw.simplr.sh/api/starships/48.json",
    "https://sw.simplr.sh/api/starships/49.json",
    "https://sw.simplr.sh/api/starships/52.json",
    "https://sw.simplr.sh/api/starships/58.json"
  ],
  "vehicles": [
    "https://sw.simplr.sh/api/vehicles/4.json",
    "https://sw.simplr.sh/api/vehicles/44.json",
    "https://sw.simplr.sh/api/vehicles/45.json",
    "https://sw.simplr.sh/api/vehicles/46.json",
    "https://sw.simplr.sh/api/vehicles/50.json",
    "https://sw.simplr.sh/api/vehicles/51.json",
    "https://sw.simplr.sh/api/vehicles/53.json",
    "https://sw.simplr.sh/api/vehicles/54.json",
    "https://sw.simplr.sh/api/vehicles/55.json",
    "https://sw.simplr.sh/api/vehicles/56.json",
    "https://sw.simplr.sh/api/vehicles/57.json"
  ],
  "species": [
    "https://sw.simplr.sh/api/species/1.json",
    "https://sw.simplr.sh/api/species/2.json",
    "https://sw.simplr.sh/api/species/6.json",
    "https://sw.simplr.sh/api/species/12.json",
    "https://sw.simplr.sh/api/species/13.json",
    "https://sw.simplr.sh/api/species/15.json",
    "https://sw.simplr.sh/api/species/28.json",
    "https://sw.simplr.sh/api/species/29.json",
    "https://sw.simplr.sh/api/species/30.json",
    "https://sw.simplr.sh/api/species/31.json",
    "https://sw.simplr.sh/api/species/32.json",
    "https://sw.simplr.sh/api/species/33.json",
    "https://sw.simplr.sh/api/species/34.json",
    "https://sw.simplr.sh/api/species/35.json"
  ],
  "created": "2014-12-20T10:57:57.886000Z",
  "edited": "2014-12-20T20:18:48.516000Z",
  "url": "https://sw.simplr.sh/api/films/5.json"
}

=== simplr-sh/sw-api/public/api/films/4.json
{
  "title": "The Phantom Menace",
  "episode_id": 1,
  "opening_crawl": "Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....",
  "director": "George Lucas",
  "producer": "Rick McCallum",
  "release_date": "1999-05-19",
  "characters": [
    "https://sw.simplr.sh/api/people/2.json",
    "https://sw.simplr.sh/api/people/3.json",
    "https://sw.simplr.sh/api/people/10.json",
    "https://sw.simplr.sh/api/people/11.json",
    "https://sw.simplr.sh/api/people/16.json",
    "https://sw.simplr.sh/api/people/20.json",
    "https://sw.simplr.sh/api/people/21.json",
    "https://sw.simplr.sh/api/people/32.json",
    "https://sw.simplr.sh/api/people/33.json",
    "https://sw.simplr.sh/api/people/34.json",
    "https://sw.simplr.sh/api/people/35.json",
    "https://sw.simplr.sh/api/people/36.json",
    "https://sw.simplr.sh/api/people/37.json",
    "https://sw.simplr.sh/api/people/38.json",
    "https://sw.simplr.sh/api/people/39.json",
    "https://sw.simplr.sh/api/people/40.json",
    "https://sw.simplr.sh/api/people/41.json",
    "https://sw.simplr.sh/api/people/42.json",
    "https://sw.simplr.sh/api/people/43.json",
    "https://sw.simplr.sh/api/people/44.json",
    "https://sw.simplr.sh/api/people/46.json",
    "https://sw.simplr.sh/api/people/47.json",
    "https://sw.simplr.sh/api/people/48.json",
    "https://sw.simplr.sh/api/people/49.json",
    "https://sw.simplr.sh/api/people/50.json",
    "https://sw.simplr.sh/api/people/51.json",
    "https://sw.simplr.sh/api/people/52.json",
    "https://sw.simplr.sh/api/people/53.json",
    "https://sw.simplr.sh/api/people/54.json",
    "https://sw.simplr.sh/api/people/55.json",
    "https://sw.simplr.sh/api/people/56.json",
    "https://sw.simplr.sh/api/people/57.json",
    "https://sw.simplr.sh/api/people/58.json",
    "https://sw.simplr.sh/api/people/59.json"
  ],
  "planets": [
    "https://sw.simplr.sh/api/planets/1.json",
    "https://sw.simplr.sh/api/planets/8.json",
    "https://sw.simplr.sh/api/planets/9.json"
  ],
  "starships": [
    "https://sw.simplr.sh/api/starships/31.json",
    "https://sw.simplr.sh/api/starships/32.json",
    "https://sw.simplr.sh/api/starships/39.json",
    "https://sw.simplr.sh/api/starships/40.json",
    "https://sw.simplr.sh/api/starships/41.json"
  ],
  "vehicles": [
    "https://sw.simplr.sh/api/vehicles/33.json",
    "https://sw.simplr.sh/api/vehicles/34.json",
    "https://sw.simplr.sh/api/vehicles/35.json",
    "https://sw.simplr.sh/api/vehicles/36.json",
    "https://sw.simplr.sh/api/vehicles/37.json",
    "https://sw.simplr.sh/api/vehicles/38.json",
    "https://sw.simplr.sh/api/vehicles/42.json"
  ],
  "species": [
    "https://sw.simplr.sh/api/species/1.json",
    "https://sw.simplr.sh/api/species/2.json",
    "https://sw.simplr.sh/api/species/6.json",
    "https://sw.simplr.sh/api/species/11.json",
    "https://sw.simplr.sh/api/species/12.json",
    "https://sw.simplr.sh/api/species/13.json",
    "https://sw.simplr.sh/api/species/14.json",
    "https://sw.simplr.sh/api/species/15.json",
    "https://sw.simplr.sh/api/species/16.json",
    "https://sw.simplr.sh/api/species/17.json",
    "https://sw.simplr.sh/api/species/18.json",
    "https://sw.simplr.sh/api/species/19.json",
    "https://sw.simplr.sh/api/species/20.json",
    "https://sw.simplr.sh/api/species/21.json",
    "https://sw.simplr.sh/api/species/22.json",
    "https://sw.simplr.sh/api/species/23.json",
    "https://sw.simplr.sh/api/species/24.json",
    "https://sw.simplr.sh/api/species/25.json",
    "https://sw.simplr.sh/api/species/26.json",
    "https://sw.simplr.sh/api/species/27.json"
  ],
  "created": "2014-12-19T16:52:55.740000Z",
  "edited": "2014-12-20T10:54:07.216000Z",
  "url": "https://sw.simplr.sh/api/films/4.json"
}

=== simplr-sh/sw-api/public/api/films/2.json
{
  "title": "The Empire Strikes Back",
  "episode_id": 5,
  "opening_crawl": "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space....",
  "director": "Irvin Kershner",
  "producer": "Gary Kurtz, Rick McCallum",
  "release_date": "1980-05-17",
  "characters": [
    "https://sw.simplr.sh/api/people/1.json",
    "https://sw.simplr.sh/api/people/2.json",
    "https://sw.simplr.sh/api/people/3.json",
    "https://sw.simplr.sh/api/people/4.json",
    "https://sw.simplr.sh/api/people/5.json",
    "https://sw.simplr.sh/api/people/10.json",
    "https://sw.simplr.sh/api/people/13.json",
    "https://sw.simplr.sh/api/people/14.json",
    "https://sw.simplr.sh/api/people/18.json",
    "https://sw.simplr.sh/api/people/20.json",
    "https://sw.simplr.sh/api/people/21.json",
    "https://sw.simplr.sh/api/people/22.json",
    "https://sw.simplr.sh/api/people/23.json",
    "https://sw.simplr.sh/api/people/24.json",
    "https://sw.simplr.sh/api/people/25.json",
    "https://sw.simplr.sh/api/people/26.json"
  ],
  "planets": [
    "https://sw.simplr.sh/api/planets/4.json",
    "https://sw.simplr.sh/api/planets/5.json",
    "https://sw.simplr.sh/api/planets/6.json",
    "https://sw.simplr.sh/api/planets/27.json"
  ],
  "starships": [
    "https://sw.simplr.sh/api/starships/3.json",
    "https://sw.simplr.sh/api/starships/10.json",
    "https://sw.simplr.sh/api/starships/11.json",
    "https://sw.simplr.sh/api/starships/12.json",
    "https://sw.simplr.sh/api/starships/15.json",
    "https://sw.simplr.sh/api/starships/17.json",
    "https://sw.simplr.sh/api/starships/21.json",
    "https://sw.simplr.sh/api/starships/22.json",
    "https://sw.simplr.sh/api/starships/23.json"
  ],
  "vehicles": [
    "https://sw.simplr.sh/api/vehicles/8.json",
    "https://sw.simplr.sh/api/vehicles/14.json",
    "https://sw.simplr.sh/api/vehicles/16.json",
    "https://sw.simplr.sh/api/vehicles/18.json",
    "https://sw.simplr.sh/api/vehicles/19.json",
    "https://sw.simplr.sh/api/vehicles/20.json"
  ],
  "species": [
    "https://sw.simplr.sh/api/species/1.json",
    "https://sw.simplr.sh/api/species/2.json",
    "https://sw.simplr.sh/api/species/3.json",
    "https://sw.simplr.sh/api/species/6.json",
    "https://sw.simplr.sh/api/species/7.json"
  ],
  "created": "2014-12-12T11:26:24.656000Z",
  "edited": "2014-12-15T13:07:53.386000Z",
  "url": "https://sw.simplr.sh/api/films/2.json"
}

=== simplr-sh/sw-api/public/api/films/1.json
{
  "title": "A New Hope",
  "episode_id": 4,
  "opening_crawl": "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
  "director": "George Lucas",
  "producer": "Gary Kurtz, Rick McCallum",
  "release_date": "1977-05-25",
  "characters": [
    "https://sw.simplr.sh/api/people/1.json",
    "https://sw.simplr.sh/api/people/2.json",
    "https://sw.simplr.sh/api/people/3.json",
    "https://sw.simplr.sh/api/people/4.json",
    "https://sw.simplr.sh/api/people/5.json",
    "https://sw.simplr.sh/api/people/6.json",
    "https://sw.simplr.sh/api/people/7.json",
    "https://sw.simplr.sh/api/people/8.json",
    "https://sw.simplr.sh/api/people/9.json",
    "https://sw.simplr.sh/api/people/10.json",
    "https://sw.simplr.sh/api/people/12.json",
    "https://sw.simplr.sh/api/people/13.json",
    "https://sw.simplr.sh/api/people/14.json",
    "https://sw.simplr.sh/api/people/15.json",
    "https://sw.simplr.sh/api/people/16.json",
    "https://sw.simplr.sh/api/people/18.json",
    "https://sw.simplr.sh/api/people/19.json",
    "https://sw.simplr.sh/api/people/81.json"
  ],
  "planets": [
    "https://sw.simplr.sh/api/planets/1.json",
    "https://sw.simplr.sh/api/planets/2.json",
    "https://sw.simplr.sh/api/planets/3.json"
  ],
  "starships": [
    "https://sw.simplr.sh/api/starships/2.json",
    "https://sw.simplr.sh/api/starships/3.json",
    "https://sw.simplr.sh/api/starships/5.json",
    "https://sw.simplr.sh/api/starships/9.json",
    "https://sw.simplr.sh/api/starships/10.json",
    "https://sw.simplr.sh/api/starships/11.json",
    "https://sw.simplr.sh/api/starships/12.json",
    "https://sw.simplr.sh/api/starships/13.json"
  ],
  "vehicles": [
    "https://sw.simplr.sh/api/vehicles/4.json",
    "https://sw.simplr.sh/api/vehicles/6.json",
    "https://sw.simplr.sh/api/vehicles/7.json",
    "https://sw.simplr.sh/api/vehicles/8.json"
  ],
  "species": [
    "https://sw.simplr.sh/api/species/1.json",
    "https://sw.simplr.sh/api/species/2.json",
    "https://sw.simplr.sh/api/species/3.json",
    "https://sw.simplr.sh/api/species/4.json",
    "https://sw.simplr.sh/api/species/5.json"
  ],
  "created": "2014-12-10T14:23:31.880000Z",
  "edited": "2014-12-20T19:49:45.256000Z",
  "url": "https://sw.simplr.sh/api/films/1.json"
}

=== simplr-sh/sw-api/public/api/films/3.json
{
  "title": "Return of the Jedi",
  "episode_id": 6,
  "opening_crawl": "Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.\r\n\r\nLittle does Luke know that the\r\nGALACTIC EMPIRE has secretly\r\nbegun construction on a new\r\narmored space station even\r\nmore powerful than the first\r\ndreaded Death Star.\r\n\r\nWhen completed, this ultimate\r\nweapon will spell certain doom\r\nfor the small band of rebels\r\nstruggling to restore freedom\r\nto the galaxy...",
  "director": "Richard Marquand",
  "producer": "Howard G. Kazanjian, George Lucas, Rick McCallum",
  "release_date": "1983-05-25",
  "characters": [
    "https://sw.simplr.sh/api/people/1.json",
    "https://sw.simplr.sh/api/people/2.json",
    "https://sw.simplr.sh/api/people/3.json",
    "https://sw.simplr.sh/api/people/4.json",
    "https://sw.simplr.sh/api/people/5.json",
    "https://sw.simplr.sh/api/people/10.json",
    "https://sw.simplr.sh/api/people/13.json",
    "https://sw.simplr.sh/api/people/14.json",
    "https://sw.simplr.sh/api/people/16.json",
    "https://sw.simplr.sh/api/people/18.json",
    "https://sw.simplr.sh/api/people/20.json",
    "https://sw.simplr.sh/api/people/21.json",
    "https://sw.simplr.sh/api/people/22.json",
    "https://sw.simplr.sh/api/people/25.json",
    "https://sw.simplr.sh/api/people/27.json",
    "https://sw.simplr.sh/api/people/28.json",
    "https://sw.simplr.sh/api/people/29.json",
    "https://sw.simplr.sh/api/people/30.json",
    "https://sw.simplr.sh/api/people/31.json",
    "https://sw.simplr.sh/api/people/45.json"
  ],
  "planets": [
    "https://sw.simplr.sh/api/planets/1.json",
    "https://sw.simplr.sh/api/planets/5.json",
    "https://sw.simplr.sh/api/planets/7.json",
    "https://sw.simplr.sh/api/planets/8.json",
    "https://sw.simplr.sh/api/planets/9.json"
  ],
  "starships": [
    "https://sw.simplr.sh/api/starships/2.json",
    "https://sw.simplr.sh/api/starships/3.json",
    "https://sw.simplr.sh/api/starships/10.json",
    "https://sw.simplr.sh/api/starships/11.json",
    "https://sw.simplr.sh/api/starships/12.json",
    "https://sw.simplr.sh/api/starships/15.json",
    "https://sw.simplr.sh/api/starships/17.json",
    "https://sw.simplr.sh/api/starships/22.json",
    "https://sw.simplr.sh/api/starships/23.json",
    "https://sw.simplr.sh/api/starships/27.json",
    "https://sw.simplr.sh/api/starships/28.json",
    "https://sw.simplr.sh/api/starships/29.json"
  ],
  "vehicles": [
    "https://sw.simplr.sh/api/vehicles/8.json",
    "https://sw.simplr.sh/api/vehicles/16.json",
    "https://sw.simplr.sh/api/vehicles/18.json",
    "https://sw.simplr.sh/api/vehicles/19.json",
    "https://sw.simplr.sh/api/vehicles/24.json",
    "https://sw.simplr.sh/api/vehicles/25.json",
    "https://sw.simplr.sh/api/vehicles/26.json",
    "https://sw.simplr.sh/api/vehicles/30.json"
  ],
  "species": [
    "https://sw.simplr.sh/api/species/1.json",
    "https://sw.simplr.sh/api/species/2.json",
    "https://sw.simplr.sh/api/species/3.json",
    "https://sw.simplr.sh/api/species/5.json",
    "https://sw.simplr.sh/api/species/6.json",
    "https://sw.simplr.sh/api/species/8.json",
    "https://sw.simplr.sh/api/species/9.json",
    "https://sw.simplr.sh/api/species/10.json",
    "https://sw.simplr.sh/api/species/15.json"
  ],
  "created": "2014-12-18T10:39:33.255000Z",
  "edited": "2014-12-20T09:48:37.462000Z",
  "url": "https://sw.simplr.sh/api/films/3.json"
}
