=== simplr-sh/sw-api/public/api/vehicles/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"model": {
			"type": "string"
		},
		"manufacturer": {
			"type": "string"
		},
		"cost_in_credits": {
			"type": "string"
		},
		"length": {
			"type": "string"
		},
		"max_atmosphering_speed": {
			"type": "string"
		},
		"crew": {
			"type": "string"
		},
		"passengers": {
			"type": "string"
		},
		"cargo_capacity": {
			"type": "string"
		},
		"consumables": {
			"type": "string"
		},
		"vehicle_class": {
			"type": "string"
		},
		"pilots": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"model",
		"manufacturer",
		"cost_in_credits",
		"length",
		"max_atmosphering_speed",
		"crew",
		"passengers",
		"cargo_capacity",
		"consumables",
		"vehicle_class",
		"pilots",
		"films",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/vehicles/8.json
{
  "name": "TIE/LN starfighter",
  "model": "Twin Ion Engine/Ln Starfighter",
  "manufacturer": "Sienar Fleet Systems",
  "cost_in_credits": "unknown",
  "length": "6.4",
  "max_atmosphering_speed": "1200",
  "crew": "1",
  "passengers": "0",
  "cargo_capacity": "65",
  "consumables": "2 days",
  "vehicle_class": "starfighter",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/1.json",
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json"
  ],
  "created": "2014-12-10T16:33:52.860000Z",
  "edited": "2014-12-20T21:30:21.670000Z",
  "url": "https://sw.simplr.sh/api/vehicles/8.json"
}

=== simplr-sh/sw-api/public/api/vehicles/60.json
{
  "name": "Tsmeu-6 personal wheel bike",
  "model": "Tsmeu-6 personal wheel bike",
  "manufacturer": "Z-Gomot Ternbuell Guppat Corporation",
  "cost_in_credits": "15000",
  "length": "3.5",
  "max_atmosphering_speed": "330",
  "crew": "1",
  "passengers": "1",
  "cargo_capacity": "10",
  "consumables": "none",
  "vehicle_class": "wheeled walker",
  "pilots": ["https://sw.simplr.sh/api/people/79.json"],
  "films": ["https://sw.simplr.sh/api/films/6.json"],
  "created": "2014-12-20T19:43:54.870000Z",
  "edited": "2014-12-20T21:30:21.745000Z",
  "url": "https://sw.simplr.sh/api/vehicles/60.json"
}

=== simplr-sh/sw-api/public/api/vehicles/7.json
{
  "name": "X-34 landspeeder",
  "model": "X-34 landspeeder",
  "manufacturer": "SoroSuub Corporation",
  "cost_in_credits": "10550",
  "length": "3.4 ",
  "max_atmosphering_speed": "250",
  "crew": "1",
  "passengers": "1",
  "cargo_capacity": "5",
  "consumables": "unknown",
  "vehicle_class": "repulsorcraft",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/1.json"],
  "created": "2014-12-10T16:13:52.586000Z",
  "edited": "2014-12-20T21:30:21.668000Z",
  "url": "https://sw.simplr.sh/api/vehicles/7.json"
}

=== simplr-sh/sw-api/public/api/vehicles/25.json
{
  "name": "Bantha-II cargo skiff",
  "model": "Bantha-II",
  "manufacturer": "Ubrikkian Industries",
  "cost_in_credits": "8000",
  "length": "9.5",
  "max_atmosphering_speed": "250",
  "crew": "5",
  "passengers": "16",
  "cargo_capacity": "135000",
  "consumables": "1 day",
  "vehicle_class": "repulsorcraft cargo skiff",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/3.json"],
  "created": "2014-12-18T10:48:03.208000Z",
  "edited": "2014-12-20T21:30:21.688000Z",
  "url": "https://sw.simplr.sh/api/vehicles/25.json"
}

=== simplr-sh/sw-api/public/api/vehicles/34.json
{
  "name": "Multi-Troop Transport",
  "model": "Multi-Troop Transport",
  "manufacturer": "Baktoid Armor Workshop",
  "cost_in_credits": "138000",
  "length": "31",
  "max_atmosphering_speed": "35",
  "crew": "4",
  "passengers": "112",
  "cargo_capacity": "12000",
  "consumables": "unknown",
  "vehicle_class": "repulsorcraft",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/4.json"],
  "created": "2014-12-19T17:12:04.400000Z",
  "edited": "2014-12-20T21:30:21.700000Z",
  "url": "https://sw.simplr.sh/api/vehicles/34.json"
}

=== simplr-sh/sw-api/public/api/vehicles/19.json
{
  "name": "AT-ST",
  "model": "All Terrain Scout Transport",
  "manufacturer": "Kuat Drive Yards, Imperial Department of Military Research",
  "cost_in_credits": "unknown",
  "length": "2",
  "max_atmosphering_speed": "90",
  "crew": "2",
  "passengers": "0",
  "cargo_capacity": "200",
  "consumables": "none",
  "vehicle_class": "walker",
  "pilots": ["https://sw.simplr.sh/api/people/13.json"],
  "films": [
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json"
  ],
  "created": "2014-12-15T12:46:42.384000Z",
  "edited": "2014-12-20T21:30:21.679000Z",
  "url": "https://sw.simplr.sh/api/vehicles/19.json"
}

=== simplr-sh/sw-api/public/api/vehicles/50.json
{
  "name": "LAAT/i",
  "model": "Low Altitude Assault Transport/infrantry",
  "manufacturer": "Rothana Heavy Engineering",
  "cost_in_credits": "unknown",
  "length": "17.4",
  "max_atmosphering_speed": "620",
  "crew": "6",
  "passengers": "30",
  "cargo_capacity": "170",
  "consumables": "unknown",
  "vehicle_class": "gunship",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T18:01:21.014000Z",
  "edited": "2014-12-20T21:30:21.723000Z",
  "url": "https://sw.simplr.sh/api/vehicles/50.json"
}

=== simplr-sh/sw-api/public/api/vehicles/46.json
{
  "name": "XJ-6 airspeeder",
  "model": "XJ-6 airspeeder",
  "manufacturer": "Narglatch AirTech prefabricated kit",
  "cost_in_credits": "unknown",
  "length": "6.23",
  "max_atmosphering_speed": "720",
  "crew": "1",
  "passengers": "1",
  "cargo_capacity": "unknown",
  "consumables": "unknown",
  "vehicle_class": "airspeeder",
  "pilots": ["https://sw.simplr.sh/api/people/11.json"],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T17:19:19.991000Z",
  "edited": "2014-12-20T21:30:21.719000Z",
  "url": "https://sw.simplr.sh/api/vehicles/46.json"
}
