=== simplr-sh/sw-api/public/api/vehicles/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"model": {
			"type": "string"
		},
		"manufacturer": {
			"type": "string"
		},
		"cost_in_credits": {
			"type": "string"
		},
		"length": {
			"type": "string"
		},
		"max_atmosphering_speed": {
			"type": "string"
		},
		"crew": {
			"type": "string"
		},
		"passengers": {
			"type": "string"
		},
		"cargo_capacity": {
			"type": "string"
		},
		"consumables": {
			"type": "string"
		},
		"vehicle_class": {
			"type": "string"
		},
		"pilots": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"model",
		"manufacturer",
		"cost_in_credits",
		"length",
		"max_atmosphering_speed",
		"crew",
		"passengers",
		"cargo_capacity",
		"consumables",
		"vehicle_class",
		"pilots",
		"films",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/vehicles/18.json
{
  "name": "AT-AT",
  "model": "All Terrain Armored Transport",
  "manufacturer": "Kuat Drive Yards, Imperial Department of Military Research",
  "cost_in_credits": "unknown",
  "length": "20",
  "max_atmosphering_speed": "60",
  "crew": "5",
  "passengers": "40",
  "cargo_capacity": "1000",
  "consumables": "unknown",
  "vehicle_class": "assault walker",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json"
  ],
  "created": "2014-12-15T12:38:25.937000Z",
  "edited": "2014-12-20T21:30:21.677000Z",
  "url": "https://sw.simplr.sh/api/vehicles/18.json"
}

=== simplr-sh/sw-api/public/api/vehicles/45.json
{
  "name": "Koro-2 Exodrive airspeeder",
  "model": "Koro-2 Exodrive airspeeder",
  "manufacturer": "Desler Gizh Outworld Mobility Corporation",
  "cost_in_credits": "unknown",
  "length": "6.6",
  "max_atmosphering_speed": "800",
  "crew": "1",
  "passengers": "1",
  "cargo_capacity": "80",
  "consumables": "unknown",
  "vehicle_class": "airspeeder",
  "pilots": ["https://sw.simplr.sh/api/people/70.json"],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T17:17:33.526000Z",
  "edited": "2014-12-20T21:30:21.716000Z",
  "url": "https://sw.simplr.sh/api/vehicles/45.json"
}

=== simplr-sh/sw-api/public/api/vehicles/44.json
{
  "name": "Zephyr-G swoop bike",
  "model": "Zephyr-G swoop bike",
  "manufacturer": "Mobquet Swoops and Speeders",
  "cost_in_credits": "5750",
  "length": "3.68",
  "max_atmosphering_speed": "350",
  "crew": "1",
  "passengers": "1",
  "cargo_capacity": "200",
  "consumables": "none",
  "vehicle_class": "repulsorcraft",
  "pilots": ["https://sw.simplr.sh/api/people/11.json"],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T16:24:16.026000Z",
  "edited": "2014-12-20T21:30:21.714000Z",
  "url": "https://sw.simplr.sh/api/vehicles/44.json"
}

=== simplr-sh/sw-api/public/api/vehicles/55.json
{
  "name": "Flitknot speeder",
  "model": "Flitknot speeder",
  "manufacturer": "Huppla Pasa Tisc Shipwrights Collective",
  "cost_in_credits": "8000",
  "length": "2",
  "max_atmosphering_speed": "634",
  "crew": "1",
  "passengers": "0",
  "cargo_capacity": "unknown",
  "consumables": "unknown",
  "vehicle_class": "speeder",
  "pilots": ["https://sw.simplr.sh/api/people/67.json"],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T18:15:20.312000Z",
  "edited": "2014-12-20T21:30:21.735000Z",
  "url": "https://sw.simplr.sh/api/vehicles/55.json"
}

=== simplr-sh/sw-api/public/api/vehicles/72.json
{
  "name": "Corporate Alliance tank droid",
  "model": "NR-N99 Persuader-class droid enforcer",
  "manufacturer": "Techno Union",
  "cost_in_credits": "49000",
  "length": "10.96",
  "max_atmosphering_speed": "100",
  "crew": "0",
  "passengers": "4",
  "cargo_capacity": "none",
  "consumables": "none",
  "vehicle_class": "droid tank",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/6.json"],
  "created": "2014-12-20T20:26:55.522000Z",
  "edited": "2014-12-20T21:30:21.765000Z",
  "url": "https://sw.simplr.sh/api/vehicles/72.json"
}

=== simplr-sh/sw-api/public/api/vehicles/16.json
{
  "name": "TIE bomber",
  "model": "TIE/sa bomber",
  "manufacturer": "Sienar Fleet Systems",
  "cost_in_credits": "unknown",
  "length": "7.8",
  "max_atmosphering_speed": "850",
  "crew": "1",
  "passengers": "0",
  "cargo_capacity": "none",
  "consumables": "2 days",
  "vehicle_class": "space/planetary bomber",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json"
  ],
  "created": "2014-12-15T12:33:15.838000Z",
  "edited": "2014-12-20T21:30:21.675000Z",
  "url": "https://sw.simplr.sh/api/vehicles/16.json"
}

=== simplr-sh/sw-api/public/api/vehicles/57.json
{
  "name": "Geonosian starfighter",
  "model": "Nantex-class territorial defense",
  "manufacturer": "Huppla Pasa Tisc Shipwrights Collective",
  "cost_in_credits": "unknown",
  "length": "9.8",
  "max_atmosphering_speed": "20000",
  "crew": "1",
  "passengers": "0",
  "cargo_capacity": "unknown",
  "consumables": "unknown",
  "vehicle_class": "starfighter",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T18:34:12.541000Z",
  "edited": "2014-12-20T21:30:21.742000Z",
  "url": "https://sw.simplr.sh/api/vehicles/57.json"
}

=== simplr-sh/sw-api/public/api/vehicles/4.json
{
  "name": "Sand Crawler",
  "model": "Digger Crawler",
  "manufacturer": "Corellia Mining Corporation",
  "cost_in_credits": "150000",
  "length": "36.8 ",
  "max_atmosphering_speed": "30",
  "crew": "46",
  "passengers": "30",
  "cargo_capacity": "50000",
  "consumables": "2 months",
  "vehicle_class": "wheeled",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/1.json",
    "https://sw.simplr.sh/api/films/5.json"
  ],
  "created": "2014-12-10T15:36:25.724000Z",
  "edited": "2014-12-20T21:30:21.661000Z",
  "url": "https://sw.simplr.sh/api/vehicles/4.json"
}
