=== simplr-sh/sw-api/public/api/vehicles/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"model": {
			"type": "string"
		},
		"manufacturer": {
			"type": "string"
		},
		"cost_in_credits": {
			"type": "string"
		},
		"length": {
			"type": "string"
		},
		"max_atmosphering_speed": {
			"type": "string"
		},
		"crew": {
			"type": "string"
		},
		"passengers": {
			"type": "string"
		},
		"cargo_capacity": {
			"type": "string"
		},
		"consumables": {
			"type": "string"
		},
		"vehicle_class": {
			"type": "string"
		},
		"pilots": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"model",
		"manufacturer",
		"cost_in_credits",
		"length",
		"max_atmosphering_speed",
		"crew",
		"passengers",
		"cargo_capacity",
		"consumables",
		"vehicle_class",
		"pilots",
		"films",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/vehicles/56.json
{
  "name": "Neimoidian shuttle",
  "model": "Sheathipede-class transport shuttle",
  "manufacturer": "Haor Chall Engineering",
  "cost_in_credits": "unknown",
  "length": "20",
  "max_atmosphering_speed": "880",
  "crew": "2",
  "passengers": "6",
  "cargo_capacity": "1000",
  "consumables": "7 days",
  "vehicle_class": "transport",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T18:25:44.912000Z",
  "edited": "2014-12-20T21:30:21.739000Z",
  "url": "https://sw.simplr.sh/api/vehicles/56.json"
}

=== simplr-sh/sw-api/public/api/vehicles/42.json
{
  "name": "Sith speeder",
  "model": "FC-20 speeder bike",
  "manufacturer": "Razalon",
  "cost_in_credits": "4000",
  "length": "1.5",
  "max_atmosphering_speed": "180",
  "crew": "1",
  "passengers": "0",
  "cargo_capacity": "2",
  "consumables": "unknown",
  "vehicle_class": "speeder",
  "pilots": ["https://sw.simplr.sh/api/people/44.json"],
  "films": ["https://sw.simplr.sh/api/films/4.json"],
  "created": "2014-12-20T10:09:56.095000Z",
  "edited": "2014-12-20T21:30:21.712000Z",
  "url": "https://sw.simplr.sh/api/vehicles/42.json"
}

=== simplr-sh/sw-api/public/api/vehicles/53.json
{
  "name": "AT-TE",
  "model": "All Terrain Tactical Enforcer",
  "manufacturer": "Rothana Heavy Engineering, Kuat Drive Yards",
  "cost_in_credits": "unknown",
  "length": "13.2",
  "max_atmosphering_speed": "60",
  "crew": "6",
  "passengers": "36",
  "cargo_capacity": "10000",
  "consumables": "21 days",
  "vehicle_class": "walker",
  "pilots": [],
  "films": [
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T18:10:07.560000Z",
  "edited": "2014-12-20T21:30:21.728000Z",
  "url": "https://sw.simplr.sh/api/vehicles/53.json"
}

=== simplr-sh/sw-api/public/api/vehicles/54.json
{
  "name": "SPHA",
  "model": "Self-Propelled Heavy Artillery",
  "manufacturer": "Rothana Heavy Engineering",
  "cost_in_credits": "unknown",
  "length": "140",
  "max_atmosphering_speed": "35",
  "crew": "25",
  "passengers": "30",
  "cargo_capacity": "500",
  "consumables": "7 days",
  "vehicle_class": "walker",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T18:12:32.315000Z",
  "edited": "2014-12-20T21:30:21.731000Z",
  "url": "https://sw.simplr.sh/api/vehicles/54.json"
}

=== simplr-sh/sw-api/public/api/vehicles/30.json
{
  "name": "Imperial Speeder Bike",
  "model": "74-Z speeder bike",
  "manufacturer": "Aratech Repulsor Company",
  "cost_in_credits": "8000",
  "length": "3",
  "max_atmosphering_speed": "360",
  "crew": "1",
  "passengers": "1",
  "cargo_capacity": "4",
  "consumables": "1 day",
  "vehicle_class": "speeder",
  "pilots": [
    "https://sw.simplr.sh/api/people/1.json",
    "https://sw.simplr.sh/api/people/5.json"
  ],
  "films": ["https://sw.simplr.sh/api/films/3.json"],
  "created": "2014-12-18T11:20:04.625000Z",
  "edited": "2014-12-20T21:30:21.693000Z",
  "url": "https://sw.simplr.sh/api/vehicles/30.json"
}

=== simplr-sh/sw-api/public/api/vehicles/14.json
{
  "name": "Snowspeeder",
  "model": "t-47 airspeeder",
  "manufacturer": "Incom corporation",
  "cost_in_credits": "unknown",
  "length": "4.5",
  "max_atmosphering_speed": "650",
  "crew": "2",
  "passengers": "0",
  "cargo_capacity": "10",
  "consumables": "none",
  "vehicle_class": "airspeeder",
  "pilots": [
    "https://sw.simplr.sh/api/people/1.json",
    "https://sw.simplr.sh/api/people/18.json"
  ],
  "films": ["https://sw.simplr.sh/api/films/2.json"],
  "created": "2014-12-15T12:22:12Z",
  "edited": "2014-12-20T21:30:21.672000Z",
  "url": "https://sw.simplr.sh/api/vehicles/14.json"
}

=== simplr-sh/sw-api/public/api/vehicles/20.json
{
  "name": "Storm IV Twin-Pod cloud car",
  "model": "Storm IV Twin-Pod",
  "manufacturer": "Bespin Motors",
  "cost_in_credits": "75000",
  "length": "7",
  "max_atmosphering_speed": "1500",
  "crew": "2",
  "passengers": "0",
  "cargo_capacity": "10",
  "consumables": "1 day",
  "vehicle_class": "repulsorcraft",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/2.json"],
  "created": "2014-12-15T12:58:50.530000Z",
  "edited": "2014-12-20T21:30:21.681000Z",
  "url": "https://sw.simplr.sh/api/vehicles/20.json"
}

=== simplr-sh/sw-api/public/api/vehicles/69.json
{
  "name": "Oevvaor jet catamaran",
  "model": "Oevvaor jet catamaran",
  "manufacturer": "Appazanna Engineering Works",
  "cost_in_credits": "12125",
  "length": "15.1",
  "max_atmosphering_speed": "420",
  "crew": "2",
  "passengers": "2",
  "cargo_capacity": "50",
  "consumables": "3 days",
  "vehicle_class": "airspeeder",
  "pilots": [],
  "films": ["https://sw.simplr.sh/api/films/6.json"],
  "created": "2014-12-20T20:20:53.931000Z",
  "edited": "2014-12-20T21:30:21.756000Z",
  "url": "https://sw.simplr.sh/api/vehicles/69.json"
}
