=== simplr-sh/sw-api/public/api/species/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"classification": {
			"type": "string"
		},
		"designation": {
			"type": "string"
		},
		"average_height": {
			"type": "string"
		},
		"skin_colors": {
			"type": "string"
		},
		"hair_colors": {
			"type": "string"
		},
		"eye_colors": {
			"type": "string"
		},
		"average_lifespan": {
			"type": "string"
		},
		"homeworld": {
			"type": "string"
		},
		"language": {
			"type": "string"
		},
		"people": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"classification",
		"designation",
		"average_height",
		"skin_colors",
		"hair_colors",
		"eye_colors",
		"average_lifespan",
		"homeworld",
		"language",
		"people",
		"films",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/species/7.json
{
  "name": "Trandoshan",
  "classification": "reptile",
  "designation": "sentient",
  "average_height": "200",
  "skin_colors": "brown, green",
  "hair_colors": "none",
  "eye_colors": "yellow, orange",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/29.json",
  "language": "Dosh",
  "people": ["https://sw.simplr.sh/api/people/24.json"],
  "films": ["https://sw.simplr.sh/api/films/2.json"],
  "created": "2014-12-15T13:07:47.704000Z",
  "edited": "2014-12-20T21:36:42.151000Z",
  "url": "https://sw.simplr.sh/api/species/7.json"
}

=== simplr-sh/sw-api/public/api/species/4.json
{
  "name": "Rodian",
  "classification": "sentient",
  "designation": "reptilian",
  "average_height": "170",
  "skin_colors": "green, blue",
  "hair_colors": "n/a",
  "eye_colors": "black",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/23.json",
  "language": "Galatic Basic",
  "people": ["https://sw.simplr.sh/api/people/15.json"],
  "films": ["https://sw.simplr.sh/api/films/1.json"],
  "created": "2014-12-10T17:05:26.471000Z",
  "edited": "2014-12-20T21:36:42.144000Z",
  "url": "https://sw.simplr.sh/api/species/4.json"
}

=== simplr-sh/sw-api/public/api/species/13.json
{
  "name": "Toydarian",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "120",
  "skin_colors": "blue, green, grey",
  "hair_colors": "none",
  "eye_colors": "yellow",
  "average_lifespan": "91",
  "homeworld": "https://sw.simplr.sh/api/planets/34.json",
  "language": "Toydarian",
  "people": ["https://sw.simplr.sh/api/people/40.json"],
  "films": [
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/5.json"
  ],
  "created": "2014-12-19T17:48:56.893000Z",
  "edited": "2014-12-20T21:36:42.165000Z",
  "url": "https://sw.simplr.sh/api/species/13.json"
}

=== simplr-sh/sw-api/public/api/species/23.json
{
  "name": "Tholothian",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "unknown",
  "skin_colors": "dark",
  "hair_colors": "unknown",
  "eye_colors": "blue, indigo",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/46.json",
  "language": "unknown",
  "people": ["https://sw.simplr.sh/api/people/55.json"],
  "films": [
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T10:29:13.798000Z",
  "edited": "2014-12-20T21:36:42.186000Z",
  "url": "https://sw.simplr.sh/api/species/23.json"
}

=== simplr-sh/sw-api/public/api/species/30.json
{
  "name": "Clawdite",
  "classification": "reptilian",
  "designation": "sentient",
  "average_height": "180",
  "skin_colors": "green, yellow",
  "hair_colors": "none",
  "eye_colors": "yellow",
  "average_lifespan": "70",
  "homeworld": "https://sw.simplr.sh/api/planets/54.json",
  "language": "Clawdite",
  "people": ["https://sw.simplr.sh/api/people/70.json"],
  "films": [
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T16:57:46.171000Z",
  "edited": "2014-12-20T21:36:42.199000Z",
  "url": "https://sw.simplr.sh/api/species/30.json"
}

=== simplr-sh/sw-api/public/api/species/28.json
{
  "name": "Geonosian",
  "classification": "insectoid",
  "designation": "sentient",
  "average_height": "178",
  "skin_colors": "green, brown",
  "hair_colors": "none",
  "eye_colors": "green, hazel",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/11.json",
  "language": "Geonosian",
  "people": ["https://sw.simplr.sh/api/people/63.json"],
  "films": [
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T16:40:45.618000Z",
  "edited": "2014-12-20T21:36:42.195000Z",
  "url": "https://sw.simplr.sh/api/species/28.json"
}

=== simplr-sh/sw-api/public/api/species/29.json
{
  "name": "Mirialan",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "180",
  "skin_colors": "yellow, green",
  "hair_colors": "black, brown",
  "eye_colors": "blue, green, red, yellow, brown, orange",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/51.json",
  "language": "Mirialan",
  "people": [
    "https://sw.simplr.sh/api/people/64.json",
    "https://sw.simplr.sh/api/people/65.json"
  ],
  "films": [
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T16:46:48.290000Z",
  "edited": "2014-12-20T21:36:42.197000Z",
  "url": "https://sw.simplr.sh/api/species/29.json"
}

=== simplr-sh/sw-api/public/api/species/21.json
{
  "name": "Nautolan",
  "classification": "amphibian",
  "designation": "sentient",
  "average_height": "180",
  "skin_colors": "green, blue, brown, red",
  "hair_colors": "none",
  "eye_colors": "black",
  "average_lifespan": "70",
  "homeworld": "https://sw.simplr.sh/api/planets/44.json",
  "language": "Nautila",
  "people": ["https://sw.simplr.sh/api/people/53.json"],
  "films": ["https://sw.simplr.sh/api/films/4.json"],
  "created": "2014-12-20T10:18:58.610000Z",
  "edited": "2014-12-20T21:36:42.181000Z",
  "url": "https://sw.simplr.sh/api/species/21.json"
}
