=== simplr-sh/sw-api/public/api/species/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"classification": {
			"type": "string"
		},
		"designation": {
			"type": "string"
		},
		"average_height": {
			"type": "string"
		},
		"skin_colors": {
			"type": "string"
		},
		"hair_colors": {
			"type": "string"
		},
		"eye_colors": {
			"type": "string"
		},
		"average_lifespan": {
			"type": "string"
		},
		"homeworld": {
			"type": "string"
		},
		"language": {
			"type": "string"
		},
		"people": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"classification",
		"designation",
		"average_height",
		"skin_colors",
		"hair_colors",
		"eye_colors",
		"average_lifespan",
		"homeworld",
		"language",
		"people",
		"films",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/species/3.json
{
  "name": "Wookie",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "210",
  "skin_colors": "gray",
  "hair_colors": "black, brown",
  "eye_colors": "blue, green, yellow, brown, golden, red",
  "average_lifespan": "400",
  "homeworld": "https://sw.simplr.sh/api/planets/14.json",
  "language": "Shyriiwook",
  "people": [
    "https://sw.simplr.sh/api/people/13.json",
    "https://sw.simplr.sh/api/people/80.json"
  ],
  "films": [
    "https://sw.simplr.sh/api/films/1.json",
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-10T16:44:31.486000Z",
  "edited": "2014-12-20T21:36:42.142000Z",
  "url": "https://sw.simplr.sh/api/species/3.json"
}

=== simplr-sh/sw-api/public/api/species/6.json
{
  "name": "Yoda's species",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "66",
  "skin_colors": "green, yellow",
  "hair_colors": "brown, white",
  "eye_colors": "brown, green, yellow",
  "average_lifespan": "900",
  "homeworld": "https://sw.simplr.sh/api/planets/28.json",
  "language": "Galactic basic",
  "people": ["https://sw.simplr.sh/api/people/20.json"],
  "films": [
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json",
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-15T12:27:22.877000Z",
  "edited": "2014-12-20T21:36:42.148000Z",
  "url": "https://sw.simplr.sh/api/species/6.json"
}

=== simplr-sh/sw-api/public/api/species/10.json
{
  "name": "Sullustan",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "180",
  "skin_colors": "pale",
  "hair_colors": "none",
  "eye_colors": "black",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/33.json",
  "language": "Sullutese",
  "people": ["https://sw.simplr.sh/api/people/31.json"],
  "films": ["https://sw.simplr.sh/api/films/3.json"],
  "created": "2014-12-18T11:26:20.103000Z",
  "edited": "2014-12-20T21:36:42.157000Z",
  "url": "https://sw.simplr.sh/api/species/10.json"
}

=== simplr-sh/sw-api/public/api/species/16.json
{
  "name": "Aleena",
  "classification": "reptile",
  "designation": "sentient",
  "average_height": "80",
  "skin_colors": "blue, gray",
  "hair_colors": "none",
  "eye_colors": "unknown",
  "average_lifespan": "79",
  "homeworld": "https://sw.simplr.sh/api/planets/38.json",
  "language": "Aleena",
  "people": ["https://sw.simplr.sh/api/people/47.json"],
  "films": ["https://sw.simplr.sh/api/films/4.json"],
  "created": "2014-12-20T09:53:16.481000Z",
  "edited": "2014-12-20T21:36:42.171000Z",
  "url": "https://sw.simplr.sh/api/species/16.json"
}

=== simplr-sh/sw-api/public/api/species/37.json
{
  "name": "Pau'an",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "190",
  "skin_colors": "grey",
  "hair_colors": "none",
  "eye_colors": "black",
  "average_lifespan": "700",
  "homeworld": "https://sw.simplr.sh/api/planets/12.json",
  "language": "Utapese",
  "people": ["https://sw.simplr.sh/api/people/83.json"],
  "films": ["https://sw.simplr.sh/api/films/6.json"],
  "created": "2014-12-20T20:35:06.777000Z",
  "edited": "2014-12-20T21:36:42.212000Z",
  "url": "https://sw.simplr.sh/api/species/37.json"
}

=== simplr-sh/sw-api/public/api/species/12.json
{
  "name": "Gungan",
  "classification": "amphibian",
  "designation": "sentient",
  "average_height": "190",
  "skin_colors": "brown, green",
  "hair_colors": "none",
  "eye_colors": "orange",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/8.json",
  "language": "Gungan basic",
  "people": [
    "https://sw.simplr.sh/api/people/36.json",
    "https://sw.simplr.sh/api/people/37.json",
    "https://sw.simplr.sh/api/people/38.json"
  ],
  "films": [
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/5.json"
  ],
  "created": "2014-12-19T17:30:37.341000Z",
  "edited": "2014-12-20T21:36:42.163000Z",
  "url": "https://sw.simplr.sh/api/species/12.json"
}

=== simplr-sh/sw-api/public/api/species/17.json
{
  "name": "Vulptereen",
  "classification": "unknown",
  "designation": "sentient",
  "average_height": "100",
  "skin_colors": "grey",
  "hair_colors": "none",
  "eye_colors": "yellow",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/39.json",
  "language": "vulpterish",
  "people": ["https://sw.simplr.sh/api/people/48.json"],
  "films": ["https://sw.simplr.sh/api/films/4.json"],
  "created": "2014-12-20T09:57:33.128000Z",
  "edited": "2014-12-20T21:36:42.173000Z",
  "url": "https://sw.simplr.sh/api/species/17.json"
}

=== simplr-sh/sw-api/public/api/species/25.json
{
  "name": "Quermian",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "240",
  "skin_colors": "white",
  "hair_colors": "none",
  "eye_colors": "yellow",
  "average_lifespan": "86",
  "homeworld": "https://sw.simplr.sh/api/planets/48.json",
  "language": "Quermian",
  "people": ["https://sw.simplr.sh/api/people/57.json"],
  "films": [
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T10:34:50.827000Z",
  "edited": "2014-12-20T21:36:42.189000Z",
  "url": "https://sw.simplr.sh/api/species/25.json"
}
