=== simplr-sh/sw-api/public/api/species/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"classification": {
			"type": "string"
		},
		"designation": {
			"type": "string"
		},
		"average_height": {
			"type": "string"
		},
		"skin_colors": {
			"type": "string"
		},
		"hair_colors": {
			"type": "string"
		},
		"eye_colors": {
			"type": "string"
		},
		"average_lifespan": {
			"type": "string"
		},
		"homeworld": {
			"type": "string"
		},
		"language": {
			"type": "string"
		},
		"people": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"films": {
			"type": "array",
			"items": [
				{
					"type": "string"
				}
			]
		},
		"created": {
			"type": "string"
		},
		"edited": {
			"type": "string"
		},
		"url": {
			"type": "string"
		}
	},
	"required": [
		"name",
		"classification",
		"designation",
		"average_height",
		"skin_colors",
		"hair_colors",
		"eye_colors",
		"average_lifespan",
		"homeworld",
		"language",
		"people",
		"films",
		"created",
		"edited",
		"url"
	]
}

=== simplr-sh/sw-api/public/api/species/32.json
{
  "name": "Kaminoan",
  "classification": "amphibian",
  "designation": "sentient",
  "average_height": "220",
  "skin_colors": "grey, blue",
  "hair_colors": "none",
  "eye_colors": "black",
  "average_lifespan": "80",
  "homeworld": "https://sw.simplr.sh/api/planets/10.json",
  "language": "Kaminoan",
  "people": [
    "https://sw.simplr.sh/api/people/72.json",
    "https://sw.simplr.sh/api/people/73.json"
  ],
  "films": ["https://sw.simplr.sh/api/films/5.json"],
  "created": "2014-12-20T17:31:24.838000Z",
  "edited": "2014-12-20T21:36:42.202000Z",
  "url": "https://sw.simplr.sh/api/species/32.json"
}

=== simplr-sh/sw-api/public/api/species/20.json
{
  "name": "Cerean",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "200",
  "skin_colors": "pale pink",
  "hair_colors": "red, blond, black, white",
  "eye_colors": "hazel",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/43.json",
  "language": "Cerean",
  "people": ["https://sw.simplr.sh/api/people/52.json"],
  "films": [
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T10:15:33.765000Z",
  "edited": "2014-12-20T21:36:42.179000Z",
  "url": "https://sw.simplr.sh/api/species/20.json"
}

=== simplr-sh/sw-api/public/api/species/8.json
{
  "name": "Mon Calamari",
  "classification": "amphibian",
  "designation": "sentient",
  "average_height": "160",
  "skin_colors": "red, blue, brown, magenta",
  "hair_colors": "none",
  "eye_colors": "yellow",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/31.json",
  "language": "Mon Calamarian",
  "people": ["https://sw.simplr.sh/api/people/27.json"],
  "films": ["https://sw.simplr.sh/api/films/3.json"],
  "created": "2014-12-18T11:09:52.263000Z",
  "edited": "2014-12-20T21:36:42.153000Z",
  "url": "https://sw.simplr.sh/api/species/8.json"
}

=== simplr-sh/sw-api/public/api/species/14.json
{
  "name": "Dug",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "100",
  "skin_colors": "brown, purple, grey, red",
  "hair_colors": "none",
  "eye_colors": "yellow, blue",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/35.json",
  "language": "Dugese",
  "people": ["https://sw.simplr.sh/api/people/41.json"],
  "films": ["https://sw.simplr.sh/api/films/4.json"],
  "created": "2014-12-19T17:53:11.214000Z",
  "edited": "2014-12-20T21:36:42.167000Z",
  "url": "https://sw.simplr.sh/api/species/14.json"
}

=== simplr-sh/sw-api/public/api/species/36.json
{
  "name": "Kaleesh",
  "classification": "reptile",
  "designation": "sentient",
  "average_height": "170",
  "skin_colors": "brown, orange, tan",
  "hair_colors": "none",
  "eye_colors": "yellow",
  "average_lifespan": "80",
  "homeworld": "https://sw.simplr.sh/api/planets/59.json",
  "language": "Kaleesh",
  "people": ["https://sw.simplr.sh/api/people/79.json"],
  "films": ["https://sw.simplr.sh/api/films/6.json"],
  "created": "2014-12-20T19:45:42.537000Z",
  "edited": "2014-12-20T21:36:42.210000Z",
  "url": "https://sw.simplr.sh/api/species/36.json"
}

=== simplr-sh/sw-api/public/api/species/1.json
{
  "name": "Human",
  "classification": "mammal",
  "designation": "sentient",
  "average_height": "180",
  "skin_colors": "caucasian, black, asian, hispanic",
  "hair_colors": "blonde, brown, black, red",
  "eye_colors": "brown, blue, green, hazel, grey, amber",
  "average_lifespan": "120",
  "homeworld": "https://sw.simplr.sh/api/planets/9.json",
  "language": "Galactic Basic",
  "people": [
    "https://sw.simplr.sh/api/people/66.json",
    "https://sw.simplr.sh/api/people/67.json",
    "https://sw.simplr.sh/api/people/68.json",
    "https://sw.simplr.sh/api/people/74.json"
  ],
  "films": [
    "https://sw.simplr.sh/api/films/1.json",
    "https://sw.simplr.sh/api/films/2.json",
    "https://sw.simplr.sh/api/films/3.json",
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/5.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-10T13:52:11.567000Z",
  "edited": "2014-12-20T21:36:42.136000Z",
  "url": "https://sw.simplr.sh/api/species/1.json"
}

=== simplr-sh/sw-api/public/api/species/5.json
{
  "name": "Hutt",
  "classification": "gastropod",
  "designation": "sentient",
  "average_height": "300",
  "skin_colors": "green, brown, tan",
  "hair_colors": "n/a",
  "eye_colors": "yellow, red",
  "average_lifespan": "1000",
  "homeworld": "https://sw.simplr.sh/api/planets/24.json",
  "language": "Huttese",
  "people": ["https://sw.simplr.sh/api/people/16.json"],
  "films": [
    "https://sw.simplr.sh/api/films/1.json",
    "https://sw.simplr.sh/api/films/3.json"
  ],
  "created": "2014-12-10T17:12:50.410000Z",
  "edited": "2014-12-20T21:36:42.146000Z",
  "url": "https://sw.simplr.sh/api/species/5.json"
}

=== simplr-sh/sw-api/public/api/species/19.json
{
  "name": "Toong",
  "classification": "unknown",
  "designation": "sentient",
  "average_height": "200",
  "skin_colors": "grey, green, yellow",
  "hair_colors": "none",
  "eye_colors": "orange",
  "average_lifespan": "unknown",
  "homeworld": "https://sw.simplr.sh/api/planets/41.json",
  "language": "Tundan",
  "people": ["https://sw.simplr.sh/api/people/50.json"],
  "films": [
    "https://sw.simplr.sh/api/films/4.json",
    "https://sw.simplr.sh/api/films/6.json"
  ],
  "created": "2014-12-20T10:08:36.795000Z",
  "edited": "2014-12-20T21:36:42.177000Z",
  "url": "https://sw.simplr.sh/api/species/19.json"
}
